# TODO: 베이스 이미지는 docs/environment.md 확정 후 반영
# GPU 불필요, 실시간성 요구 (시스템명세서 3.1절)
FROM ros:jazzy-ros-base

# TODO: MoveIt2, doosan-robot2, ros2_control 설치 단계 추가

WORKDIR /ros2_ws
COPY . /ros2_ws/src/control

# TODO: colcon build 및 entrypoint 구성
