<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>control</name>
  <version>0.0.1</version>
  <description>ROS2 스킬 실행기(pick/place_into) 및 순응제어. robot_state/safety_events 발행</description>
  <maintainer email="jje320594@gmail.com">jje</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_copyright</buildtool_depend>
  <buildtool_depend>ament_flake8</buildtool_depend>
  <buildtool_depend>ament_pep257</buildtool_depend>
  <buildtool_depend>python3-pytest</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sort_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
